version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app 
    depends_on:
      - mongo 
  mongo:
    image: mongo
    ports:
      - "27017:27017" 
      
#     volumes:
#       - mongodb_data:/data/db
# volumes:
#   mongodb_data: 